version: "3.9"

services:
  notification-service:
    build: ./notification-service
    ports:
      - "8081:8081"

  task-service:
    build: ./task-service
    ports:
      - "8080:8080"
    environment:
      NOTIFICATION_SERVICE_URL: http://notification-service:8081
    depends_on:
      - notification-service